### ISSUE TITLE
Make key docs more obvious

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq-docs#103]
I've noticed that some key docs are hard to find. When we start pushing the DAO through the Bisq program, we want resources to be as easy to find as possible.

What do you think about adding a 'Quick Links' section to the top of the index page, with graphical buttons to stand out from the text links below?

The screenshot below is a quick, rough approximation to show the idea. Graphics can be improved, etc.

![screenshot from 2019-02-12 18-36-21](https://user-images.githubusercontent.com/735155/52713472-65585180-2f65-11e9-9c80-ff874b86ecfd.png)

**Comment by ManfredKarrer** [comment]
@pedromvpg Could you add some graphics here?

**Comment by ManfredKarrer** [comment]
@m52go Can you merge that even if the graphics are missing?

**Comment by m52go** [comment]
Completed with #108 and refined with #111.
