### ISSUE TITLE
Improvement suggestion for user-dao-intro.adoc

### ISSUE THREAD

**Issue by basnappl** [bisq-network/bisq-docs#129]
The link to the BSQ transaction on the BSQ explorer doesn't pull up anything meaningful.  It might be a problem with the explorer or it might be a bad link.

Link text:  that same transaction on a BSQ block explorer
Link destination:  https://explorer.bisq.network/tx.html?tx=92df3183d3c60983492983882642145ac0ab8ef93cda07ff57d1f810e34003f6

**Comment by m52go** [comment]
Ah, thanks, will do this. The existing link is for a testnet transaction which doesn't exist on mainnet.
