### ISSUE TITLE
Add Bisq Telegram Group Getting Started page?

### ISSUE THREAD

**Issue by sgornick** [bisq-network/bisq-docs#141]
Is there a reason the [Bisq Telegram Group](https://t.me/bisq_p2p) is not shown on the [Getting Started](https://docs.bisq.network/getting-started.html) page like the other communications methods such as Slack or the Bisq Subreddit?

Specifically:

*"Get help and stay in touch"*

*"If you get stuck, reach out! There’s a community of people to help you on the Bisq forum, the /r/bisq subreddit, and the Bisq Slack team."*

- https://github.com/bisq-network/bisq-docs/blob/master/getting-started.adoc

Along the same lines, the Bisq.network site, such as the [Community](https://bisq.network/community) page, is missing the Telegram group as well.

And the social media icons in the footer of each page.

*"JOIN BISQ"*

github, twitter, youtube, slack, forum, mailinglist, irc, reddit

**Comment by HarryMacfinned** [comment]
afaik, Telegram is not much used by Bisq contributors.
So it may not be a good idea to promote Telegram, where so few contributors are effectively present.
There is active support on the discourse forum, on the slack, on reddit, that's already a lot for a small team as now.

**Comment by m52go** [comment]
As @HarryMacfinned said, Telegram is a community-maintained channel, not one most core contributors frequent. 

If the channel grows into one that is worth listing at some point, we could certainly list it.
