### ISSUE TITLE
Document how to setup and configure Bisq to connect with your own full node

### ISSUE THREAD

**Issue by devinbileck** [bisq-network/bisq-docs#181]
We should document the necessary configuration required for running your own full node.

For example, with the latest release of bitcoin core (0.19.0.1), the -peerbloomfilters configuration option must be set to true, as per https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.19.0.1.md:

> To eliminate well-known denial-of-service vectors in Bitcoin Core, especially for nodes with spinning disks, the default value for the -peerbloomfilters configuration option has been changed to false. This prevents Bitcoin Core from sending the BIP111 NODE_BLOOM service flag, accepting BIP37 bloom filters, or serving merkle blocks or transactions matching a bloom filter. Users who still want to provide bloom filter support may either set the configuration option to true to re-enable both BIP111 and BIP37 support or enable just BIP37 support for specific peers using the updated -whitelist and -whitebind configuration options described elsewhere in these release notes. For the near future, lightweight clients using public BIP111/BIP37 nodes should still be able to connect to older versions of Bitcoin Core and nodes that have manually enabled BIP37 support, but developers of such software should consider migrating to either using specific BIP37 nodes or an alternative transaction filtering system. (#16152)

**Comment by devinbileck** [comment]
Additionally, the node must not be pruned. See https://github.com/bisq-network/bisq/issues/3273

**Comment by m52go** [comment]
See https://bisq.wiki/Connecting_to_your_own_Bitcoin_node. Closing as complete.
