### ISSUE TITLE
Add Translator documentation

### ISSUE THREAD

**Issue by arunasurya** [bisq-network/bisq-docs#183]
@y3v63n and I created Translator documentation in this repo on my personal github site: https://github.com/arunasurya/bisqtransifex

We would like these three documents to be part of official Bisq documentation. This will help new translators get started with the project and encourage current translators to contribute with their ideas for improving the project.

**Comment by m52go** [comment]
@arunasurya agreed! What needs to happen to integrate these documents? Are they ready to go as-is?

**Comment by arunasurya** [comment]
Yes they are for now. I am planning to keep working on them and involve other contributors. Thanks!

**Comment by m52go** [comment]
Documentation is now ready to integrate, per conversation with Aruna earlier today. Pull requests coming soon.

**Comment by m52go** [comment]
Done at https://bisq.wiki/Translation and maintained by translations admin mwithm.
