### ISSUE TITLE
Google search: Old trading fee in whitepaper leads to misbelief

### ISSUE THREAD

**Issue by stopfeds** [bisq-network/bisq-docs#207]
I recently had an experience with someone who told me that he won't trade on Bisq because the general trading fees of 0.0019 BTC are way too high. The reason for that misbelief is, that he googled "bisq fees" & clicked on the whitepaper/fee section (one of the first results). As you all know, in the whitepaper it still says that the fees are exorbitantly high.

```
Bisq operates with the following fees:

Create offer fee: 0.001 BTC (paid to the arbitrators, mining fee is included)

Take offer fee: same as create offer fee (and also paid to the arbitrators)

Bitcoin mining fee: 0.0003 BTC (A mining fee is included in a transaction three times: Deposit from external wallet, trade, and withdrawal to external wallet. So the sum is 0.0009 BTC)

Security deposit (might be used as arbitration fee): 0.1 BTC, which is returned in whole to the trader after the transaction in case he is not found to have behaved dishonestly. The security deposit from dishonest trader will be used to pay the arbitrator for his efforts. In rare cases half the security deposit of each trader may be collected instead. The active arbitration fee is not related to the size of the trade and does not affect the time required to mediate a dispute as the amount of work an arbitrator must perform is roughly constant even when small amounts are exchanged.
```
Source: https://docs.bisq.network/exchange/whitepaper.html#fees

I don't want to know how many potential traders got detained to trade by this Google result. The trading fees are way lower and I'd say that for smaller amounts, Bisq is, during a low fee market, one of the cheapest ways to buy Bitcoin as the withdraw fee can be determined on your own.

For that reason, I'd suggest to either delete this page or make clear (with a warning box etc.) that the current trading fees can be found on the wiki.

Please note:
If you are on the whitepaper index and click on fees, you'll get forwarded to the updated wiki (https://bisq.wiki/Trading_fees). But Google still shows the old page with wrong information.

Screenshot of the Google results:
![bisqfees](https://user-images.githubusercontent.com/71401614/105405793-d7df0b00-5c2b-11eb-83cb-4e60f6d818e9.jpg)
First result doesn't really help. 2nd result is the old whitepaper. 3rd result wrong fees (super old report). 4th result link to correct fees.

**Comment by m52go** [comment]
Thanks for bringing this up...wasn't aware of it. Will probably delete as soon as DAO docs are migrated, since DAO docs are the only reason the docs website is still online.

**Comment by MwithM** [comment]
Go duck go!
![imagen](https://user-images.githubusercontent.com/50149324/105465025-b402e000-5c92-11eb-9bee-066d66e3642e.png)

**Comment by stopfeds** [comment]
Unfortunately, it's still a top search result.
Just had another conversation about Bisq and the horrible fees were mentioned again because of this.

Created this commit: https://github.com/bisq-network/bisq-docs/commit/a0ae4cfb74a4ebc6a0bc16670d44a091c5402ecc

I don't know when the DAO docs get migrated but I think this is a good workaround if it's possible to deploy that change.

**Comment by m52go** [comment]
Taken care of with https://github.com/bisq-network/bisq-docs/commit/c3dc52fa62aa2bdfb5162cb6d7b147dcdc916055 (implicit ACK with minor wording change).
