### ISSUE TITLE
Reason for payment - conflicting information

### ISSUE THREAD

**Issue by krvi** [bisq-network/bisq-docs#208]
The bisq app for windows lists this message upon start.
![image](https://user-images.githubusercontent.com/27792771/111397825-22c05080-86ba-11eb-8411-0556d74c8b0a.png)
The docs however recommend the opposite.
https://github.com/bisq-network/bisq-docs/blob/master/trading-rules.adoc#bitcoin-buyers

> Enter the trade ID in payment’s "reason for payment"
> 
> If possible, the trade ID should be included in the payment’s "reason for payment" field. The name of this field can vary by payment method; some call it "Message" or "Information for recipient" or similar. Pick the field (if available) that enables the user to tie the payment to the specific trade.
> 
> If there is no such field, just send the payment without specifying the trade ID.

Can this be resolved?

**Comment by m52go** [comment]
Yes docs.bisq.network isn't maintained...all up-to-date information is on bisq.wiki. Most links on the front page of docs.bisq.network already point to the wiki.

I'm working on making the final remaining transitions to the wiki, and then the docs site will be shut down.
