### ISSUE TITLE
Produce 'Secure Your Wallet' doc

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq-docs#58]
At a minimum, this document should help people secure their Bisq wallets by helping them:

- [x] set a password to enable encryption
- [x] save their wallet's seed words so that it can be restored later

Once that's done, perhaps this document could grow into a more general reference on wallet security.

**Comment by cbeams** [comment]
Closing as complete with the merge of #45. Thanks, @m52go.

**Comment by cbeams** [comment]
From https://docs.bisq.network/secure-wallet.html:

![image](https://user-images.githubusercontent.com/301810/40615170-f2261780-6285-11e8-919c-5fc8e03f8bc1.png)

**Comment by cbeams** [comment]
I promoted this new doc via Twitter at https://twitter.com/bisq_network/status/1001815611733954560:

![image](https://user-images.githubusercontent.com/301810/40723116-65ae8b9e-641e-11e8-9523-db0abed3fd51.png)
