### ISSUE TITLE
Improvement suggestion for getting-started.adoc

### ISSUE THREAD

**Issue by Mark-BC** [bisq-network/bisq-docs#63]
Since only the BTC-selling side of a BTC-from-fiat transaction is controlled/tracked by BISQ, what prevents the BTC seller from taking the fiat payment, but denying the fiat payment was ever made (ie. not registering it with BISQ) causing the buyer to get nothing and lose their deposit?

Would love to know the answer,
markbc1@gmail.com

**Comment by Mark-BC** [comment]
No, it is clear.   I hadn't read the documentation about the arbitration
process when I wrote that email.

I now understand.
Thanks!
Mark

**Comment by m52go** [comment]
Cool! FWIW, more thorough docs for the arbitration process are on the horizon.

**Comment by cbeams** [comment]
Closing as complete (with no change necessary to the docs).
