### ISSUE TITLE
Produce a Rules doc

### ISSUE THREAD

**Issue by m52go** [bisq-network/bisq-docs#80]
Continuing [this discussion](https://github.com/bisq-network/bisq-website/issues/78). 

The mandate of the Rules doc is broader, meant to cover rules for all trades (not just F2F) as well as arbitration, so it makes sense to designate 1 place in this repo to discuss the whole thing.

For now the Rules doc is a placeholder (as soon as [this](https://github.com/bisq-network/bisq-docs/pull/81) is merged). **I've linked to this issue at the top of the placeholder for people to get updates.**

After the placeholder is merged, I'll open a [WIP] PR that works toward a complete Rules doc.

**Comment by m52go** [comment]
@ManfredKarrer how imminent is the update to the trading protocol without arbitrators? 

I'd like to finish this doc and get rid of this issue...so if it's going to happen soon, maybe I shouldn't add details about arbitration.

**Comment by ManfredKarrer** [comment]
@m52go A team has started working on it. It requires the DAO to be launched so I would estimate about 3 months.
Regarding the rules: There will be no so much change in the new model, just that the mediator plays the role fo the arbitrator and has no "executive" power. 
There will be likely also a period where we need to support both protocols. Don't know the details yet how we will do that...

**Comment by m52go** [comment]
Cool...sounds like arbitration details will still be useful for some time, so I'll include them.

**Comment by cbeams** [comment]
> Cool...sounds like arbitration details will still be useful for some time, so I'll include them.

Yes, please do. We need a good place to point people to on this, and there really isn't anything at the moment.

**Comment by m52go** [comment]
This was finally completed with #167.
